 - hosts: localhost 
   become: yes
   tasks:
   - name: Comment line
     ansible.builtin.replace:
       path: /etc/sysconfig/network-scripts/ifcfg-eth0
       #get the string to search for comment
       regexp: '^[^#](.*IPADDR.*|.*NETMASK.*)'
       #comment out the line
       replace: '# \1'
       backup: yes
  
   - name: replace word
     ansible.builtin.replace:
       path: /etc/sysconfig/network-scripts/ifcfg-eth0
       #get the string to search for replace
       after: 'BOOTPROTO='
       before: '\n'
       regexp: '.*'
       replace: 'dhcp'
       backup: yes

 
   - name: network restart
     ansible.builtin.service:
       name: networkd
       state: restarted
